#!/usr/bin/env bash
# Script to configure localhost and facebook.com IP addresses

# Make sure the script runs as root
if [[ $EUID -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

HOSTS_FILE="/etc/hosts"
BACKUP_FILE="/etc/hosts.bak"

# Backup the hosts file
cp "$HOSTS_FILE" "$BACKUP_FILE"

# Remove any previous custom entries for localhost or facebook.com
sed -i '/127\.0\.0\.2 localhost/d' "$HOSTS_FILE"
sed -i '/8\.8\.8\.8 facebook\.com/d' "$HOSTS_FILE"

# Add new entries
echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
