#!/usr/bin/env bash
# Configure localhost to 127.0.0.2 and facebook.com to 8.8.8.8

HOSTS_FILE="/etc/hosts"

# Make sure we run as root
if [[ $EUID -ne 0 ]]; then
    echo "Please run as root"
    exit 1
fi

# Remove old entries if they exist
sed -i '/127\.0\.0\.2 localhost/d' $HOSTS_FILE
sed -i '/8\.8\.8\.8 facebook\.com/d' $HOSTS_FILE

# Add new entries
echo "127.0.0.2 localhost" >> $HOSTS_FILE
echo "8.8.8.8 facebook.com" >> $HOSTS_FILE
